#!/usr/bin/env python

import sys
import polib
from bs4 import BeautifulSoup


xlat={}
po = polib.pofile(sys.argv[1])
for entry in po:
    xlat[entry.msgid] = entry.msgstr

soup = BeautifulSoup(sys.stdin.read(), "html.parser")
# soup = BeautifulSoup(sys.stdin.read(), "xml")

for t in soup.findAll('text'):
    if len(t.text)==0: continue
    s = t.string.strip()
    t.string = xlat.get(s, "UNTRANSLATED")

print(soup.prettify("cp1251"))
