#!/usr/bin/perl

use warnings;
use strict;

my %xlat;
# load po
warn "reading $ARGV[0]";
open F, '<', $ARGV[0] or die;
my ($id, $str) = (undef, undef);
while(<F>)
{
  $id = $1 if m/^msgid "(.*)"/i;
  $str = $1 if m/^msgstr "(.*)"/i;
  if (defined $id and defined $str)
  {
    $id =~ s/\\"/"/g;
    $str =~ s/\\"/"/g;
    $xlat{$id} = $str;
    # warn "$id, $str";
    ($id, $str) = (undef, undef);
  }
}
close F;

# die;

# read STDIN
while(<STDIN>)
{
  s!(<text\b[^>]*>)\s*(\S.*\S)\s*(</text\b)!$1$xlat{$2}$3!;
  print;
}
