#!/usr/bin/env python

import sys
import polib
import re

xlat={}
po = polib.pofile(sys.argv[1])
for entry in po:
    xlat[entry.msgid] = entry.msgstr

def find_xlat(mo):
    line = mo.group(0)
    text = mo.group(3).strip()
    if len(text)==0: return line
    if xlat.has_key(text):
        return mo.group(1) + xlat[text].encode("cp1251") + mo.group(4)
    else:
        return line

for line in sys.stdin:
    print re.sub("(<(\w+)>)(.*)(</\\2>)", find_xlat, line),
