#!/usr/bin/perl

use warnings;
use strict;
use Text::Iconv;
my $converter = Text::Iconv->new("UTF8", "CP1251");

my %xlat;
# load po
# warn "reading $ARGV[0]";
open F, '<', $ARGV[0] or die;
my ($id, $str) = (undef, undef);
while(<F>)
{
  $id = $1 if m/^msgid "(.*)"/i;
  $str = $1 if m/^msgstr "(.*)"/i;
  if (defined $id and defined $str)
  {
    $id =~ s/\\"/"/g;
    $str =~ s/\\"/"/g;
    $xlat{$id} = $converter->convert($str);
    # warn "$id, $str";
    ($id, $str) = (undef, undef);
  }
}
close F;

# die;

my $trans = 0;
my $untrans = 0;
# read STDIN
while(<STDIN>)
{
  if(m!(<text\b[^>]*>)\s*(\S.*\S)\s*(</text\b)!)
  {
    if($xlat{$2})
    {
      s!(<text\b[^>]*>)\s*(\S.*\S)\s*(</text\b)!$1$xlat{$2}$3!;
      $trans++;
    }
    else
    {
      $untrans++;
    }
  }
  print;
}

warn "Translated: $trans\n";
warn "Untranslated: $untrans\n";
